/** Declaration file generated by dts-gen */

export function isIp(ip:string):number;

export function isIpv4(ip:string):boolean;

export function isIpv6(ip:string):boolean;

export function parseIp(ip:string):Array<string>;

